# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "maxvirtus"
description: > # this means to ignore newlines until "email:"
  Masculine Matters

email: maxvirtus@gmail.com
#blog logo
logo: "/assets/images/kDNYb5GW.jpeg"
# blog cover
cover: "/assets/images/tower-bridge.jpg"

name: 'Max Virtus'
author: 'Max Virtus'
author_image: "/assets/images/kDNYb5GW.jpeg"

paginate:	5

url: "http://maxvirtus.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/maxvirtus
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/maxvirtus
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
